### PR TITLE
Fix for : #11 - List View with null pointer exception

### PR DESCRIPTION
**Pull request by sarvaratchagan**

### CODE REVIEW

**Comment by mrg** [comment]
Thanks for finding the issue and the pull-request.  Are you an Apache committer (have an ICLA on file)?  I looked on https://people.apache.org/phonebook.html but couldn't find a match for you.

Since this project will be part of Apache Cayenne (and in fact is in the process of being migrated there -- we just set up the repository and GitHub mirror [1] and I will seed it with the code from this project), we can only accept contributions from Apache members with an ICLA filed.  Information on the ICLA can be found at https://www.apache.org/licenses/#clas.

Thanks!

[1] https://github.com/apache/cayenne-modeler.

**Comment by sarvaratchagan** [comment]
Hello Michael Gentry, 
               I'm trying to contribute with cayenne. Right now I'm trying to understand existing code.  I know cayenne modeler is part of the cayenne project. If really ICLA needed  can you help me to file ICLA ? So that I can work with you.

Thanks!

**Comment by mrg** [comment]
Follow the instructions at https://www.apache.org/licenses/#clas to fill out and sign the ICLA PDF, then return it to the ASF (instructions in the PDF).  Once filed/accepted, we can accept code contributions.  Let me know when you've filed it, so I can be on the lookout for it.

Thanks!

mrg

PS. The new repository has been created and the GitHub mirror is at https://github.com/apache/cayenne-modeler if you want to clone it instead of this one.

**Comment by sarvaratchagan** [comment]
I have already submit signed document to community. Thanks

**Comment by mrg** [comment]
Great!  I'll be on the lookout for it.

I forgot to mention you might also want to join the Cayenne mailing lists (developer and user) where most discussion happens: http://cayenne.apache.org/mailing-lists.html

Also, I pushed everything from CMP over to https://github.com/apache/cayenne-modeler so it would be best to clone that and delete CMP.  CMP is now officially dead.  :-)

**Comment by mrg** [comment]
Hi Sarva, I saw your ICLA come through and I incorporated your fix on https://github.com/apache/cayenne-modeler.  I'm going to close this pull request since this repository is dead now.  Thanks!

**Pull request closed without merging**
